colo ron
syn on
se ai ar nu rnu 
se mouse=a bs=2 ts=4 sw=4 ttm=100
se makeprg=g++\ -Wall\ -Wshadow\ -O2\ -std=c++0x\ -o\ %<\ %
au BufNewFile *.cpp 0r ~/default.cpp | :1,$-7 fo
filetype indent on

map <F7> <ESC>:wa<CR>:make!<CR>
imap <F7> <ESC>:wa<CR>:make!<CR>
map <F8> :cope <CR>
map <S-F8> :ccl <CR>
map <F9> :!./%< <CR>
map <C-F9> :!./%< < %<.in <CR>
map <C-F7> <ESC>:tabe %<.in<CR>

