colo ron
syn on
se ai ar nu rnu 
se mouse=a bs=2 ts=4 sw=4 ttm=100
se makeprg=g++\ -Wall\ -Wshadow\ -O2\ -std=c++0x\ -o\ %<\ %
au BufNewFile *.cpp 0r ~/default.cpp | :1,$-7 fo
filetype indent on

map <f6> :call CompileRunGpp()<cr>
func! CompileRunGpp()
	exec "w"
	exec "!g++ -std=c++14 % -o %<"
	exec "! ./%<"
endfunc